import { FLYER_PAGE_H, FLYER_PAGE_W } from './constants';
import type { FlyerDocument, FlyerTemplate } from './types';
import { newElementId } from './types';

const blankDoc = (title: string): FlyerDocument => ({
  version: 1,
  title,
  pages: [{ background: '#ffffff', elements: [] }],
});

export const FLYER_TEMPLATES: FlyerTemplate[] = [
  {
    id: 'blank',
    name: 'Leer',
    description: 'Weiße Leinwand',
    preview: '#ffffff',
    document: blankDoc('Neuer Flyer'),
  },
  {
    id: 'school-classic',
    name: 'Schule Klassisch',
    description: 'Ruhig & seriös',
    preview: '#f7f6f3',
    previewGradient: 'linear-gradient(180deg, #f7f6f3 0%, #0d6b6e 100%)',
    document: {
      version: 1,
      title: 'Ankündigung',
      pages: [
        {
          background: '#f7f6f3',
          elements: [
            {
              id: newElementId(),
              type: 'rect',
              x: 0,
              y: 0,
              width: FLYER_PAGE_W,
              height: 8,
              rotation: 0,
              zIndex: 1,
              fill: '#0d6b6e',
            },
            {
              id: newElementId(),
              type: 'text',
              x: 56,
              y: 48,
              width: 680,
              height: 40,
              rotation: 0,
              zIndex: 2,
              text: 'JOHANNES-GYMNASIUM · LAHNSTEIN',
              fontSize: 11,
              fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
              fontWeight: 600,
              letterSpacing: 3,
              color: '#5c5c5c',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'text',
              x: 56,
              y: 120,
              width: 680,
              height: 120,
              rotation: 0,
              zIndex: 3,
              text: 'Titel der\nAnkündigung',
              fontSize: 52,
              fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
              fontWeight: 300,
              lineHeight: 1.05,
              color: '#1c1c1c',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 56,
              y: 250,
              width: 120,
              height: 4,
              rotation: 0,
              zIndex: 4,
              fill: '#0d6b6e',
              borderRadius: 2,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 56,
              y: 280,
              width: 520,
              height: 200,
              rotation: 0,
              zIndex: 5,
              text: 'Hier steht dein Text: Termin, Ort, wer mitmachen kann und was mitgebracht werden soll.',
              fontSize: 18,
              fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
              fontWeight: 400,
              lineHeight: 1.55,
              color: '#2c3e50',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 56,
              y: 520,
              width: FLYER_PAGE_W - 112,
              height: 200,
              rotation: 0,
              zIndex: 6,
              fill: 'rgba(13, 107, 110, 0.08)',
              borderRadius: 12,
              stroke: 'rgba(13, 107, 110, 0.2)',
              strokeWidth: 1,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 80,
              y: 560,
              width: 620,
              height: 120,
              rotation: 0,
              zIndex: 7,
              text: '📅 Datum · 🕐 Uhrzeit · 📍 Ort',
              fontSize: 22,
              fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
              fontWeight: 600,
              lineHeight: 1.6,
              color: '#0d6b6e',
              textAlign: 'left',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'sport-energy',
    name: 'Sport & AG',
    description: 'Dynamisch & kräftig',
    preview: '#ff6b35',
    previewGradient: 'linear-gradient(135deg, #ff6b35 0%, #004d40 100%)',
    document: {
      version: 1,
      title: 'Sport-AG',
      pages: [
        {
          background: '#0a1628',
          backgroundGradient: 'linear-gradient(165deg, #0a1628 0%, #004d40 45%, #00897b 100%)',
          elements: [
            {
              id: newElementId(),
              type: 'circle',
              x: 520,
              y: -80,
              width: 360,
              height: 360,
              rotation: 0,
              zIndex: 1,
              fill: 'rgba(255, 107, 53, 0.35)',
            },
            {
              id: newElementId(),
              type: 'circle',
              x: -60,
              y: 680,
              width: 280,
              height: 280,
              rotation: 0,
              zIndex: 2,
              fill: 'rgba(0, 172, 193, 0.25)',
            },
            {
              id: newElementId(),
              type: 'text',
              x: 48,
              y: 72,
              width: 700,
              height: 48,
              rotation: 0,
              zIndex: 3,
              text: 'NEU · ANMELDUNG OFFEN',
              fontSize: 14,
              fontWeight: 800,
              letterSpacing: 4,
              color: '#ff6b35',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'text',
              x: 48,
              y: 130,
              width: 700,
              height: 160,
              rotation: 0,
              zIndex: 4,
              text: 'CALISTHENICS\nAG',
              fontSize: 72,
              fontWeight: 900,
              lineHeight: 0.95,
              color: '#ffffff',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 48,
              y: 310,
              width: 698,
              height: 280,
              rotation: 0,
              zIndex: 5,
              fill: 'rgba(255,255,255,0.12)',
              borderRadius: 20,
              stroke: 'rgba(255,255,255,0.25)',
              strokeWidth: 2,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 72,
              y: 340,
              width: 650,
              height: 220,
              rotation: 0,
              zIndex: 6,
              text: 'Kraft, Koordination & Teamgeist.\nJeden Mittwoch · Sporthalle\nFür Klassen 5–10',
              fontSize: 24,
              fontWeight: 500,
              lineHeight: 1.5,
              color: '#e0f7fa',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 48,
              y: 620,
              width: 320,
              height: 56,
              rotation: 0,
              zIndex: 7,
              fill: '#ff6b35',
              borderRadius: 28,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 48,
              y: 632,
              width: 320,
              height: 40,
              rotation: 0,
              zIndex: 8,
              text: 'Jetzt mitmachen!',
              fontSize: 20,
              fontWeight: 800,
              color: '#ffffff',
              textAlign: 'center',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'party-pop',
    name: 'Party Pop',
    description: 'Bunt & fröhlich',
    preview: '#ff1493',
    previewGradient: 'linear-gradient(135deg, #667eea 0%, #f5576c 100%)',
    document: {
      version: 1,
      title: 'Event Flyer',
      pages: [
        {
          background: '#fff0f6',
          backgroundGradient: 'linear-gradient(145deg, #667eea 0%, #764ba2 40%, #f5576c 100%)',
          elements: [
            {
              id: newElementId(),
              type: 'text',
              x: 48,
              y: 80,
              width: 698,
              height: 200,
              rotation: -4,
              zIndex: 2,
              text: 'KARNEVAL\n2026',
              fontSize: 88,
              fontWeight: 900,
              lineHeight: 0.9,
              color: '#ffffff',
              textAlign: 'center',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 98,
              y: 300,
              width: 598,
              height: 340,
              rotation: 2,
              zIndex: 3,
              fill: '#ffffff',
              borderRadius: 24,
              opacity: 0.95,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 130,
              y: 340,
              width: 534,
              height: 260,
              rotation: 2,
              zIndex: 4,
              text: '🎭 Minigames · 🎨 Kostümwettbewerb\n🍩 Berliner · 🎵 Musik\n\nFreitag, 14.02. · Aula',
              fontSize: 26,
              fontWeight: 600,
              lineHeight: 1.55,
              color: '#1a237e',
              textAlign: 'center',
            },
            {
              id: newElementId(),
              type: 'text',
              x: 48,
              y: 720,
              width: 698,
              height: 60,
              rotation: 0,
              zIndex: 5,
              text: 'Alle willkommen — mitmachen & staunen!',
              fontSize: 22,
              fontWeight: 700,
              color: '#fff59d',
              textAlign: 'center',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'workshop-grid',
    name: 'Workshop',
    description: 'Infokästen & Foto',
    preview: '#3949ab',
    previewGradient: 'linear-gradient(180deg, #e3f2fd 0%, #3949ab 100%)',
    document: {
      version: 1,
      title: 'Workshop',
      pages: [
        {
          background: '#e3f2fd',
          elements: [
            {
              id: newElementId(),
              type: 'rect',
              x: 0,
              y: 0,
              width: FLYER_PAGE_W,
              height: 200,
              rotation: 0,
              zIndex: 1,
              fill: '#3949ab',
            },
            {
              id: newElementId(),
              type: 'text',
              x: 56,
              y: 56,
              width: 680,
              height: 100,
              rotation: 0,
              zIndex: 2,
              text: 'Workshop-Titel',
              fontSize: 44,
              fontWeight: 800,
              color: '#ffffff',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 56,
              y: 230,
              width: 320,
              height: 240,
              rotation: 0,
              zIndex: 3,
              fill: '#ffffff',
              borderRadius: 16,
              stroke: '#c5cae9',
              strokeWidth: 2,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 76,
              y: 252,
              width: 280,
              height: 200,
              rotation: 0,
              zIndex: 4,
              text: 'Was?\nKurzbeschreibung des Angebots.',
              fontSize: 18,
              fontWeight: 500,
              lineHeight: 1.5,
              color: '#1a237e',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 416,
              y: 230,
              width: 320,
              height: 240,
              rotation: 0,
              zIndex: 5,
              fill: '#ffffff',
              borderRadius: 16,
              stroke: '#c5cae9',
              strokeWidth: 2,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 436,
              y: 252,
              width: 280,
              height: 200,
              rotation: 0,
              zIndex: 6,
              text: 'Wann?\nDatum, Uhrzeit, Raum.',
              fontSize: 18,
              fontWeight: 500,
              lineHeight: 1.5,
              color: '#1a237e',
              textAlign: 'left',
            },
            {
              id: newElementId(),
              type: 'rect',
              x: 56,
              y: 500,
              width: FLYER_PAGE_W - 112,
              height: 320,
              rotation: 0,
              zIndex: 7,
              fill: '#bbdefb',
              borderRadius: 16,
              stroke: '#90caf9',
              strokeWidth: 2,
            },
            {
              id: newElementId(),
              type: 'text',
              x: 56,
              y: 640,
              width: FLYER_PAGE_W - 112,
              height: 48,
              rotation: 0,
              zIndex: 8,
              text: '📷 Bild hier einfügen (Tab „Bilder“)',
              fontSize: 20,
              fontWeight: 600,
              color: '#1565c0',
              textAlign: 'center',
            },
          ],
        },
      ],
    },
  },
];

export function getTemplateById(id: string): FlyerTemplate | undefined {
  return FLYER_TEMPLATES.find((t) => t.id === id);
}
